frase =input("ingrese una frase: ")
frase = frase.lower()
frase = frase.replace("á", "a")
frase = frase.replace("é", "e")
frase = frase.replace("í", "i")
frase = frase.replace("ó", "o")
frase = frase.replace("ú", "u")
frase = frase.replace("-", " ")
frase = frase.replace("_", " ")
frase = frase.replace(",", " ")
frase = frase.replace(".", " ")
print (frase)